/**
 * Auto-generated contract map
 * Generated by: generate-contract-imports.js
 * Do not edit manually - this file is regenerated on each deployment
 */

export const contractMap: Record<string, () => Promise<any>> = {
  'hello_world': () => import('@/contracts/hello_world'),
  'increment': () => import('@/contracts/increment'),
  'token': () => import('@/contracts/token'),
  'Hello World': () => import('@/contracts/hello_world'),
  'Increment': () => import('@/contracts/increment'),
  'Token': () => import('@/contracts/token'),
};

/**
 * Get a list of all available contract names
 */
export function getAvailableContracts(): string[] {
  return ['hello_world', 'increment', 'token'];
}
